language: node_js
sudo: false
node_js:
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
branches:
  only:
  - develop
  - master 
script:
  - npm test
deploy:
  provider: npm
  email: user@xbranch.si
  skip_cleanup: true
  api_key:
    secure: Cqf+IwM5muU3ABS41RqSYKSTLJLrfazFwmr92OcCPpfqIy6LmIPrTAPah07gjdbzgxg0ZUxEpxTXHbGwBy6kSbht4bteOqYTl6wkJhGCwAlqe+u63An6JAXofU9fr7lOZhb6MV3XL4Rha3p8IDjTTsHps9B27yviT2gD6zPpZX3ISvPRWZU30jZETb57JJ8/7cbl3S7E193lW9KwMRqMj1p5HVau0NTzwnz4Qy7W37FpqirtKFfw9AkhVy4r81q5S6RFvcLff/xddI33ocLPEB8+LWHwq/VmbsnODLlhCvB4/fGC8N5KHkEf3bEn5G5tkhOMWXjtLsE+W9yXmfgEnsFofXvd6y2v3Bf4HtMXmfW3YVtfYWLmNoJVJmShPOB3Hvz0PVh2I5b5D176zwdNMjrOPu/pfYgSI1+zw2Mk46YQVHWrgvamlNgcmOLkTAeLelizObp2wae/JYLSaODOEk92HZ6P3Q2XwZerCgsH66viCdAw2IED9FVqOuaKbjAH4cAZ1pIvwo3PvHiGBJfxUTzD8lvlLiPBh21mRsYFUoil6K8XaPZiQzmDBgKZEOGxq0fdTD2PqStVLAvQBA1Bj1woiyczYL0tf1vxTAK9JQajhKmeII6tDyPR45WhDLTNiT/ZLJ2fuExYmxqSS6pvxJPwiDokro4nbxz8dWmFpkk=
  on:
    tags: true
    repo: xbranch/ngitflow
    node: '6'
